# Generated by Django 2.2.2 on 2019-09-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rack', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=16, null=True, unique=True)),
                ('Name', models.CharField(max_length=100, null=True, unique=True)),
                ('Sale_Price', models.CharField(max_length=100, null=True, unique=True)),
                ('Stock', models.CharField(max_length=16, null=True, unique=True)),
                ('Catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.catagory')),
                ('Rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.rack')),
                ('Sub_Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subcatagory')),
                ('Warehousse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.warehouse')),
            ],
        ),
    ]
