# Generated by Django 2.2.2 on 2019-09-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_item_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Stock',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
