# Generated by Django 2.2.2 on 2019-09-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190925_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='Rack',
        ),
    ]
