# Generated by Django 2.2.2 on 2019-09-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_warehouse_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.rack'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Sub_Catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subcatagory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.warehouse'),
        ),
    ]
